import tensorflow as tf
it = tf.python_io.tf_record_iterator("car.tfrecords")
example = next(it)
print(tf.train.Example.FromString(example))
example = next(it)
print(tf.train.Example.FromString(example))
example = next(it)
print(tf.train.Example.FromString(example))
example = next(it)
print(tf.train.Example.FromString(example))
example = next(it)
print(tf.train.Example.FromString(example))
example = next(it)
print(tf.train.Example.FromString(example))
